### ISSUE TITLE
Nothing from dotnet/runtime is showing up in source.dot.net

### ISSUE THREAD

**Issue by stephentoub** [dotnet/source-indexer#103]
e.g.
<img width="263" alt="image" src="https://user-images.githubusercontent.com/2642209/184895099-9fbd7d18-fcad-4e1c-aaa8-cf0106ad938f.png">

**Comment by stephentoub** [comment]
@alexperovich, @garath, this is broken again as of this morning.

**Comment by garath** [comment]
> this is broken again as of this morning.

Site is up again, though still using an older index from August 8.

**Comment by stephentoub** [comment]
Fixed
