### ISSUE TITLE
Certificate expired on https://source.dot.net/

### ISSUE THREAD

**Issue by DanielCordell** [dotnet/source-indexer#129]
When I try to navigate to https://source.dot.net/ on `2024-01-08`, chrome tells me the connection to the site is insecure. It seems that the cookie has expired yesterday, `2024-01-07`

![image](https://github.com/dotnet/source-indexer/assets/16806427/e2a6896c-8311-4c6e-b0b4-4e06d4a6d33c)

**Comment by DanielCordell** [comment]
@garath sorry to tag you, but I saw your issue https://github.com/dotnet/dnceng/issues/408 and felt this may be relevant?

**Comment by stephentoub** [comment]
This should be fixed now. Thanks, @garath.
