### ISSUE TITLE
System.Windows.Forms is missing

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/source-indexer#138]
Not sure how long it's been missing, but it seems that all of winforms is absent. For example:

![Screenshot of source.dot.net showing "No results found" for the query "System.Windows.Forms.Application"](https://github.com/dotnet/source-indexer/assets/278957/0030ad33-fab4-4549-b16a-76d1815b18f3)

**Comment by Philip-Wang01** [comment]
Verified on the latest website (http://source.dot.net) that this issue has been fixed.
![image](https://github.com/user-attachments/assets/8045349b-27fe-41f5-8608-aa01261b9554)

**Comment by radical** [comment]
> Verified on the latest website (http://source.dot.net) that this issue has been fixed.

Closing based on that.

**Comment by PathogenDavid** [comment]
> this issue has been fixed.

Indeed it has, thanks for the heads up!

And thanks to @directhex since it looks like he was the one who fixed it 💜

**Comment by PathogenDavid** [comment]
@Philip-Wang01 @radical It seems things still aren't quite right with WinForms. For example references in `System.Windows.Forms` to methods/types in `System.Windows.Forms.Primitives` do not resolve.

For example, see [`Application.SetHighDpiMode`](https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/Application.cs,6136ea006bb780d3). Clicking on `ScaleHelper.SetProcessHighDpiMode` does not navigate to them as you'd expect.

You can manually navigate to it by searching for it, so the type was indexed it's just the cross reference link is missing for some reason. (The references are also broken in the other direction -- `SetProcessHighDpiMode` is never referenced outside of documentation according to the source browser.)

This is true of many other things in this file, such as `RunMessageLoop`, all the `PInvoke` methods, `msoloop`, etc. (`RunMessageLoop` stands out as it appears to be from the same assembly, so not sure what's up with it.)
