### ISSUE TITLE
Site isn't loading pages

### ISSUE THREAD

**Issue by tannergooding** [dotnet/source-indexer#156]
Search currently finds pages but won't load them if the search result is selected
![image](https://github.com/dotnet/source-indexer/assets/10487869/2d2f2a4b-742d-4fdb-8598-1343af86a162)

**Comment by directhex** [comment]
OK, this looks like an Azure config error after this morning's big merge. The latest PR build running the same code from a different storage account is working (https://netsourceindex-validation.azurewebsites.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Vector128_1.cs,a7d647b6968ad0f9)

**Comment by directhex** [comment]
The staging slot works too, so the issue is specific to prod. Great, love that for me. https://netsourceindex-staging.azurewebsites.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Vector128_1.cs,a7d647b6968ad0f9

**Comment by directhex** [comment]
Is... is prod running a different version of the code to staging?

**Comment by directhex** [comment]
It was, in fact, running an old site
