### ISSUE TITLE
cmake is missing from build machines

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/source-indexer#17]
After https://github.com/dotnet/source-indexer/pull/15 we still have 2 repos failing to build. (https://mseng.visualstudio.com/Tools/_build/results?buildId=7742669&view=logs)

It looks like if you can get CMAKE on the build machine, we would get past this and I can look at any remaining issues

` CMake is a pre-requisite to build this repository but it was not found on the path. Please install CMake from http://www.cmake.org/download/ and ensure it is on your path.`

@alexperovich can you please help with that?

cc @stephentoub

**Comment by danmosemsft** [comment]
https://github.com/dotnet/source-indexer/issues/12

**Comment by danmosemsft** [comment]
@alexperovich I don't know much about how this works but I see the build happened on `Pool:
DotNet-HelixVS2017` so it doesn't surprise me that CMAKE isn't there. What if we switch to `Pool:
DotNet-Build` -- is there anything the indexing part might need that isn't there? It's OK if tests don't work -- they should be disabled - looks like they are only running now for corfxelab.

**Comment by danmosemsft** [comment]
I would try it but this pool isn't listed in the dropdown for this mseng project. ..?

**Comment by alexperovich** [comment]
I sent a build on the Hosted pool to see if that works.

**Comment by danmosemsft** [comment]
```
2018-11-14T23:46:03.1464866Z      at Microsoft.SourceBrowser.Common.Log.WriteToFile(String message, String filePath).
2018-11-14T23:46:03.1465139Z   23:46:03 Failed to generate references file for: D:\a\1\s\bin\index\index\AllScenarioTests\R\d66e2395e758e06a.txt
2018-11-14T23:46:03.1465345Z   System.IO.IOException: There is not enough space on the disk.
```

**Comment by alexperovich** [comment]
yep, I put it back. Is there a way we can make the thing work without cmake available? Nothing the indexer needs requires native stuff built.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/coreclr/pull/21040

**Comment by danmosemsft** [comment]
fixed
