### ISSUE TITLE
Files (and thus the type(s) within the files) that have backtick T in the name don't work

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/source-indexer#176]
```
IHubContext`T.cs
```

e.g. `IHubContext<THub, T>` or https://source.dot.net/Microsoft.AspNetCore.SignalR.Core/IHubContext%60T.cs.html fails with a 404.

**Comment by ericstj** [comment]
I wonder if this change regressed it.  https://github.com/dotnet/source-indexer/commit/de1546cba53a9b1c76cb10c9b4537f895495d846

That touched the codepath of the webservice that is responsible for forwarding to the backing storage blob.  cc @radical

**Comment by ericstj** [comment]
Fixed in #177
