### ISSUE TITLE
source.dot.net not getting updated

### ISSUE THREAD

**Issue by stephentoub** [dotnet/source-indexer#27]
The indexed source hasn't been updated in two weeks, e.g. https://source.dot.net/#System.Private.Xml shows Dec 11th as the indexed date.

cc: @danmosemsft, @alexperovich

**Comment by danmosemsft** [comment]
Well it's not @stephentoub turn this time..

Seems like we need some kind of alert when the index doesn't build.

**Comment by stephentoub** [comment]
Is it possible builds are getting deployed to a staging server and then not to release?
