### ISSUE TITLE
Links to lots of types aren't working

### ISSUE THREAD

**Issue by stephentoub** [dotnet/source-indexer#29]
e.g. go to https://source.dot.net/#System.Collections.Immutable/System/Collections/Immutable/KeysOrValuesCollectionAccessor.cs,c51dc7e26095bf20, and notice that you can't click on the `IEnumerable<T>`,  `ICollection`, etc.

cc: @danmosemsft, @alexperovich

**Comment by KirillOsenkov** [comment]
I think the problem here is this:

```
C:\source-indexer\bin\repo\corefx\Directory.Build.targets: (40, 5): The tools directory [C:\source-indexer\bin\repo\corefx\Tools/] does not exist. Please run build -InitTools in your repo to ensure the tools are installed before attempting to build an individual project.
```

The script that prepares the repos needs to run Init after cloning.

Also I'm seeing this:

```
Exec
    Assembly = Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    CommandLineArguments = cmd /c "pushd . & "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat" & popd & build -SkipTests /p:buildnative=false -- /p:BuildPackages=false"
    Parameters
        Command = cmd /c "pushd . & "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat" & popd & build -SkipTests /p:buildnative=false -- /p:BuildPackages=false"
        WorkingDirectory = C:\source-indexer\bin/repo/corefx/
        IgnoreStandardErrorWarningFormat = True
        LogStandardErrorAsError = False
        IgnoreExitCode = True
    **********************************************************************
    ** Visual Studio 2017 Developer Command Prompt v15.9.3
    ** Copyright (c) 2017 Microsoft Corporation
    **********************************************************************
    C:\source-indexer\bin\repo\corefx\eng\build.ps1 : Parameter cannot be processed because the parameter name '' is 
    ambiguous. Possible matches include: -ArchGroup -Release -TargetGroup -OSGroup -BuildAllConfigurations -RuntimeOS 
    -OuterLoop -SkipTests -Restore -Clean -BuildTests -Test -Coverage -InitTools -ExtraArgs -Verbose -Debug -ErrorAction 
    -WarningAction -InformationAction -ErrorVariable -WarningVariable -InformationVariable -OutVariable -OutBuffer 
    -PipelineVariable.
        + CategoryInfo          : InvalidArgument: (:) [build.ps1], ParentContainsErrorRecordException
        + FullyQualifiedErrorId : AmbiguousParameter,build.ps1
     
    The command "cmd /c "pushd . & "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat" & popd & build -SkipTests /p:buildnative=false -- /p:BuildPackages=false"" exited with code 1.
```

There seems to be some weirdness with the command line (perhaps the inner `"` should be escaped somehow?)

**Comment by KirillOsenkov** [comment]
![image](https://user-images.githubusercontent.com/679326/50865643-6e994180-135b-11e9-8749-a81e0a3551f9.png)

**Comment by KirillOsenkov** [comment]
Should it be `build -SkipTests /p:buildnative=false /p:BuildPackages=false --`?

**Comment by KirillOsenkov** [comment]
or rather `build -InitTools -SkipTests /p:buildnative=false /p:BuildPackages=false`?

**Comment by KirillOsenkov** [comment]
I've ran the above and that helped some.

Now running into the issue where links like IEnumerable don't work. This is because System.Collections.Immutable.csproj when loaded has 0 references.

Somehow these aren't getting resolved:

```
    <Reference Include="System.Collections" />
    <Reference Include="System.Diagnostics.Contracts" />
    ...
```

**Comment by KirillOsenkov** [comment]
Aha, looks like if I build the .csproj from command line the references start working somewhat.

Should it be `build -InitTools & build -SkipTests /p:buildnative=false /p:BuildPackages=false`?

**Comment by stephentoub** [comment]
It looks like the command-line broke when corefx moved to arcade.

@ViktorHofer, can you help?  Why would -InitTools be necessary?  What's the minimal command-line needed to only build as little as possible, focusing primarily on the managed src components (i.e.  we don't want or need test, don't want or need packages, etc.)?

**Comment by KirillOsenkov** [comment]
I'm actually running HtmlGenerator and the error comes from MSBuildWorkspace. But maybe it was because the build script was broken and now that you've fixed it it will no longer be an issue?

**Comment by KirillOsenkov** [comment]
There's also `/p:TargetGroup=netcoreapp` and `/p:RunApiCompat=false` that's specified to HtmlGenerator - maybe we need this at the script step as well?

**Comment by KirillOsenkov** [comment]
https://github.com/dotnet/source-indexer/blob/d15febaac7999cea6ab0c4aefb336886defc1b1d/src/index/index.proj#L94-L95

**Comment by stephentoub** [comment]
TargetGroup=netcoreapp is the default for the build.  And the RunApiCompat could be specified but isn't needed, whereas it was (at least when I added it) for HtmlGenerator because of warnings that were generated and that were breaking HtmlGenerator without it.

**Comment by ViktorHofer** [comment]
Sure happy to help. `build /p:buildnative=false` should be the command that you desire. You don't need SkipTests as tests are not built and run with this command. Also you don't need buildpackages as we also don't build packages by default. I'm just trying out if buildnative=false works fine.

**Comment by stephentoub** [comment]
Fixed.
