### ISSUE TITLE
See if https://github.com/dotnet/corefx/pull/34385 breaks source indexer

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/source-indexer#34]
I was alerted to the fact that https://github.com/dotnet/corefx/pull/34385 may break source indexer. We should see if any changes are necessary on the source-indexer side to accommodate it.

**Comment by stephentoub** [comment]
@ViktorHofer, can you take care of submitting a PR to source-indexer with the updated command-line that's needed?

**Comment by ViktorHofer** [comment]
I'm on holiday till Tuesday 😭

**Comment by safern** [comment]
I can give a hand if needed. Just let me know if it indeed broke the source-indexer.

**Comment by stephentoub** [comment]
It's definitely broken; corefx isn't showing up in the index at all.  Will submit a PR to try to fix...

**Comment by ViktorHofer** [comment]
Can you point me to the place where corefx is built here?

**Comment by stephentoub** [comment]
https://github.com/dotnet/source-indexer/blame/master/src/index/repositories.props#L14

**Comment by ViktorHofer** [comment]
I see you removed /p:BuildPackages=false. Was that intentional?

**Comment by stephentoub** [comment]
> I see you removed /p:BuildPackages=false. Was that intentional?

We don't build packages by default, do we?

**Comment by stephentoub** [comment]
Oh, ugh, I see we do:
https://github.com/dotnet/corefx/blob/c8e44c3d027d0539e7f9091336cc48e59e7d03e8/build.proj#L10
Will put it back.

**Comment by ViktorHofer** [comment]
Thanks :)
