### ISSUE TITLE
source.dot.net is down

### ISSUE THREAD

**Issue by stephentoub** [dotnet/source-indexer#37]
It just shows up as a blank page with the title "Site Under Construction" 😦 

![image](https://user-images.githubusercontent.com/2642209/56043966-3adc0800-5d0c-11e9-82f3-533424813558.png)

cc: @danmosemsft, @alexperovich, @dotnet/dnceng

**Comment by MattGal** [comment]
Seems to be back now, I’ll synch with Alex when he gets in to understand what happened.

**Comment by stephentoub** [comment]
Thanks, @MattGal.
