### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by tannergooding** [dotnet/source-indexer#40]
The website is currently down and only displays a "Site Under Construction" title for a blank screen.

![SiteDown](https://user-images.githubusercontent.com/10487869/63971826-4da56e00-ca5c-11e9-8aa7-384f195e0012.jpg)

This was also raised by a few community members on the C# Discord channel.

**Comment by stephentoub** [comment]
cc: @danmosemsft, @alexperovich

**Comment by alexperovich** [comment]
Hrm, It looks like the previous deployment left the `app_offline.htm` in the website directory. For some reason MSDeploy didn't remove it when the deployment was finished.

**Comment by alexperovich** [comment]
I just deleted the file and the site is back up.

**Comment by stephentoub** [comment]
Thanks, Alex.
