### ISSUE TITLE
Add WPF's C++ sources to source-index

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/source-indexer#42]
https://github.com/dotnet/source-indexer/blob/9bff716508ba262c9583ad86c30ada7b1a07e8c8/src/index/repositories.props#L29-L36

Currently, only `*.csproj` are indexed from https://github.com/dotnet/wpf. WPF consists of `.vcxproj` (C++, C++/CLI) projects as well - can we include them in indexing as well? 

/cc @dotnet/wpf-developers

**Comment by alexperovich** [comment]
The source indexer doesn't support C++. It doesn't have any way of indexing source code that isn't processable by Roslyn.

**Comment by KirillOsenkov** [comment]
Yes I'm afraid this is non-actionable without a very significant time investment (is there even a "Roslyn" for C++?).

**Comment by weltkante** [comment]
It may be possible to look at the managed part of the mixed mode assembly via Roslyn and together with the pdb reassociate the symbols with line numbers in the source? I didn't check which Roslyn API the indexer uses, so I can't judge how much work that would be.
