### ISSUE TITLE
Anything under dotnet/runtime won't show up

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/source-indexer#47]
The projects are being recognised but it appears that there's no source codes. None of the query examples listed on the starting page does not work. 
![image](https://user-images.githubusercontent.com/42944058/78827013-6677f800-7a1d-11ea-9614-4dc36cf7f7ac.png)

**Comment by alexperovich** [comment]
There are currently issues with the design time build that SourceBrowser runs on the runtime code due to recent changes in the dotnet/runtime build. We are tracking fixing this in this issue https://github.com/dotnet/core-eng/issues/9537.

I will update this issue once we get this resolved.

**Comment by kirsan31** [comment]
Any news?
Currently:
![image](https://user-images.githubusercontent.com/17767561/81188333-dd24f880-8fbd-11ea-840c-7a15f0fceebd.png)
but no [SystemFonts.Windows.cs](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Drawing.Common/src/System/Drawing/SystemFonts.Windows.cs)

**Comment by Gnbrkm41** [comment]
It does look like the general issue is resolved, but that's one of my request as well; it would be nice if we could display all platform-specific codes instead of choosing just one (It used to show Windows codes but now it displays Unix).

**Comment by stephentoub** [comment]
> Any news?

This issue was fixed.

source.dot.net is only able to show one platform's code. By design that's currently Linux. Hopefully in the future that restriction will be lifted, likely via multiple hosts.

**Comment by Gnbrkm41** [comment]
It happened again: #53
