### ISSUE TITLE
Add ASP.NET Core source code

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/source-indexer#5]
It would be nice to also add ASP.NET Core's source code to this website. 

I can help make this happen if you need help. I made some minor changes to SourceBrowser to support indexing from project.json since ASP.NET Core 1.0 and 1.1 were built using PJ instead of MSBuild. See https://github.com/natemcmaster/aspnetsourcebrowser.

cc @alexperovich

**Comment by KirillOsenkov** [comment]
This comment in particular summarizes the current blocking issues:
https://github.com/aspnet/AspNetCore/issues/7281#issuecomment-461242879

**Comment by stephentoub** [comment]
This is done, right?
