### ISSUE TITLE
Update to 3.1/5.0

### ISSUE THREAD

**Issue by marcusturewicz** [dotnet/source-indexer#50]
I see the site is on `netcoreapp2.1`, thoughts about updating to 3.1/5.0? Happy to have a crack at this.

**Comment by alexperovich** [comment]
I don't have a problem reviewing a PR for this. It should be done in https://github.com/KirillOsenkov/SourceBrowser first though.

**Comment by marcusturewicz** [comment]
It seems to be already at 3.1 in KirillOsenkov/SourceBrowser:

https://github.com/KirillOsenkov/SourceBrowser/blob/master/src/SourceIndexServer/SourceIndexServer.csproj#L4

So maybe it should get merged in to here?

**Comment by alexperovich** [comment]
Ahh, yea. Okay, i'll get that merged into here.

**Comment by alexperovich** [comment]
The SourceBrowser code used for source.dot.net has been updated.
