### ISSUE TITLE
Anything under dotnet/runtime won't show up *again*

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/source-indexer#53]
Related (Same issue, but happened again): #47 
Example:
![image](https://user-images.githubusercontent.com/42944058/81819395-39fa5300-956a-11ea-9668-13ab1336137e.png)

**Comment by Gnbrkm41** [comment]
....Apparently this is even worse, because the projects do not show up unlike the previous issue where the assembly/projects did show up.

**Comment by alexperovich** [comment]
The dotnet/runtime build changed.... again. I'm working on a fix.

**Comment by alexperovich** [comment]
This has been fixed.
