### ISSUE TITLE
source.dot.net hasn't been updated in a month

### ISSUE THREAD

**Issue by stephentoub** [dotnet/source-indexer#57]
Looks like it's missing changes from the last month. Is the build broken?

**Comment by alexperovich** [comment]
It is... I thought I had set up notifications for this.

It is hitting some weird azure problem. I'll try to figure out the problem.

**Comment by stephentoub** [comment]
Thanks.

**Comment by alexperovich** [comment]
The build has been fixed. It was fallout from the strange tenant changes that were made in azure.
