### ISSUE TITLE
WPF sources are missing

### ISSUE THREAD

**Issue by tannergooding** [dotnet/source-indexer#58]
The dotnet/wpf repo should be included as per https://github.com/dotnet/source-indexer/blob/master/src/index/repositories.props#L21, however certain assemblies like Microsoft.DotNet.Wpf appear to be missing: https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/Dispatcher.cs; https://source.dot.net/#q=Dispatcher

**Comment by JesperTreetop** [comment]
I thought this was fixed before but it's definitely back now. PasswordBox query on [.NET Core browser](https://source.dot.net/#q=PasswordBox); [.NET Framework browser](https://referencesource.microsoft.com/#q=PasswordBox).

@alexperovich fixed this previously in #53 .

**Comment by alexperovich** [comment]
The build for wpf is currently spiting out  `error : Version 5.0.100-rc.1.20452.10 of the .NET Core SDK requires at least version 16.8.0 of MSBuild. The current available version of MSBuild is 16.7.0.37604. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.`

**Comment by directhex** [comment]
Marking closed, it seems fine right now
