### ISSUE TITLE
ReadOnlyCollectionBase is missing

### ISSUE THREAD

**Issue by kirsan31** [dotnet/source-indexer#59]
`ReadOnlyCollectionBase` is missing. For example: https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/FormCollection.cs,31d88d427ce374ce
In .Net framework indexer: https://referencesource.microsoft.com/#mscorlib/system/collections/readonlycollectionbase.cs,8a1b95dcb893d31f

**Comment by alexperovich** [comment]
closing as dupe of #60.
