### ISSUE TITLE
Things under dotnet/runtime won't show up

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/source-indexer#60]
Example Link:
https://source.dot.net/#q=Span%3CT%3E

![image](https://user-images.githubusercontent.com/42944058/88400220-fd1cc900-ce02-11ea-903b-2931327f190f.png)

cc @alexperovich

**Comment by alexperovich** [comment]
dotnet/runtime is broken yet again because the runtime team changed the build. @ViktorHofer this command no longer works `build.cmd -subset clr.corelib+libs.depprojs+libs.ref+libs.src -binarylog -os Linux -ci /p:ILLinkTrimAssembly=false`. What should be used instead?

**Comment by ViktorHofer** [comment]
Uff sorry I forgot to update the command even though I had a yodo in my PR.
