### ISSUE TITLE
dotnet/extensions doesn't seem to be getting indexed

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/source-indexer#61]
I can't, for example, find this type: https://github.com/dotnet/extensions/blob/52b4a202090891dd254ae83ab97b01a99b5f0eb9/src/HttpClientFactory/Http/src/DefaultHttpMessageHandlerBuilder.cs

**Comment by PathogenDavid** [comment]
source.dot.net is having issues in general right now, see #60

**Comment by martincostello** [comment]
Hello from the future space year 2024 - it still doesn't appear to be included by https://github.com/dotnet/source-indexer/blob/main/src/index/repositories.props.

I was looking for types related to the new resilience libraries.

**Comment by directhex** [comment]
Closed by https://github.com/dotnet/source-indexer/pull/160
