### ISSUE TITLE
Consider indexing dotnet/performance

### ISSUE THREAD

**Issue by tannergooding** [dotnet/source-indexer#63]
It might be beneficial to start indexing dotnet/performance to more readily do performance investigations and triage by correlating the two repositories.

This should largely just be adding the repo into https://github.com/dotnet/source-indexer/blob/master/src/index/repositories.props, from what I recall.

**Comment by tannergooding** [comment]
CC. @DrewScoggins, @AndyAyersMS, @kunalspathak, @adamsitnik

**Comment by DrewScoggins** [comment]
Maybe we should just go ahead and open this PR?

**Comment by alexperovich** [comment]
A PR would be welcome.

**Comment by tannergooding** [comment]
I'll submit the PR, I just wanted to log an issue first to ensure there wasn't any pushback/etc 😄
