### ISSUE TITLE
ASP.NET Core types are no longer available

### ISSUE THREAD

**Issue by a-ctor** [dotnet/source-indexer#64]
![image](https://user-images.githubusercontent.com/5082673/88799899-7facdc00-d1a7-11ea-9967-47546f6c1819.png)

The types for ASP.NET Core are no longer available on the source browser. About one week ago its was still possible to search for ASP.NET Core types.

Were they intentionally removed? And if so is there another source code browser that can be used instead?

**Comment by alexperovich** [comment]
This was not intentionally removed, the aspnetcore build was changed enough to break the indexer. I will fix it.

**Comment by alexperovich** [comment]
This is now fixed
