### ISSUE TITLE
System.Windows.Forms is broken again

### ISSUE THREAD

**Issue by kirsan31** [dotnet/source-indexer#70]
<details>
  <summary>Almost only tests there</summary>

![image](https://user-images.githubusercontent.com/17767561/98090742-824d5a80-1e95-11eb-9ff4-540fdee9c835.png)
</details>

Also about tests. Can you some how completely exclude them from source.dot.net?

**Comment by KirillOsenkov** [comment]
Someone recently contributed ability to exclude tests from indexing. But one would need to do an investigation on how to do it in the source.dot.net environment.

@alexperovich 

Maybe @RussKie knows someone who'd be interested in assisting with this?

**Comment by RussKie** [comment]
> Someone recently contributed ability to exclude tests from indexing

I've briefly looked at the repo, and couldn't see where/how it was done. If you could point me to it, it may be a quick fix.

**Comment by KirillOsenkov** [comment]
Here's the PR where support for ignoring test projects was added:
https://github.com/KirillOsenkov/SourceBrowser/pull/146

The fork of SourceBrowser used to populate https://source.dot.net is here:
https://github.com/dotnet/source-indexer/tree/master/src/SourceBrowser

Here's WinForms:
https://github.com/dotnet/source-indexer/blob/e63b37a2b6ca6d30d1c53b4ba3e2809943c39e76/src/index/repositories.props#L15-L20

This is where I'd add the argument to HtmlGenerator.exe:
https://github.com/dotnet/source-indexer/blob/e63b37a2b6ca6d30d1c53b4ba3e2809943c39e76/src/index/index.proj#L116

**Comment by KirillOsenkov** [comment]
But I think that fork needs to be updated to the latest SourceBrowser master. There really shouldn't be many changes and I think there's a script that auto-updates:

https://github.com/dotnet/source-indexer/blob/master/src/update-source-browser.ps1

**Comment by stephentoub** [comment]
We should really upstream whatever changes are in the fork and then delete it and just use Kirill's directly. Is there a reason other than "just work" we can't do that?

**Comment by alexperovich** [comment]
The fork source.dot.net uses includes 2 main changes. It supports re-mapping type-forwards that runtime uses all over the place so when you click on things in corelib, you actually get the implementation. This code is rather time consuming and not very useful outside of source.dot.net so I never sent it upstream.

The second change is to exclude all reference assemblies that get built by runtime. That could be upstreamed but its very specific to how runtime builds assemblies, so potentially not something that can be shared.

**Comment by alexperovich** [comment]
I also added support for hosting the index files in an azure storage container, rather than locally on the web server. I don't believe I have upstreamed that yet, but it would be easy to do.

**Comment by stephentoub** [comment]
Support for following type forwards, excluding reference assemblies, and hosting index files in Azure all seem to me like valuable improvements to upstream, but I'll defer to @KirillOsenkov.

**Comment by alexperovich** [comment]
While I believe "excluding reference assemblies" would be useful in upstream, the implementation is currently "is the project in a folder called 'ref'" so very tailored to what runtime does.

**Comment by alexperovich** [comment]
wpf also has some "cycle-breaker" projects that I needed to skip.

**Comment by stephentoub** [comment]
@alexperovich, what are the next steps in being able to uncomment:
https://github.com/dotnet/source-indexer/blob/7d06ed56962babdacb590c30d9faae8a2e6973f8/src/index/repositories.props#L17-L25
?

**Comment by alexperovich** [comment]
I can uncomment it as is and see what happens, I have fixed a bug since I did that. Otherwise I will need to go to winforms and enable the source index step that runtime uses.

**Comment by alexperovich** [comment]
winforms is back.

**Comment by stephentoub** [comment]
Thanks!

**Comment by alexperovich** [comment]
And the build immediately after the one I checked hit this:
11:11:38 Exception during Project file generation: D:\workspace\_work\1\s\bin\repo\winforms\src\System.Windows.Forms.Design\src\System.Windows.Forms.Design.csproj
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

It looks like I will have to get winforms on the new stuff for this to not fail with some regularity.

**Comment by kirsan31** [comment]
@alexperovich Thank you! And I think I need a word from you when to close this ;)

**Comment by KirillOsenkov** [comment]
Is the process 64-bit? Strange that it would fail with OOM.

**Comment by KirillOsenkov** [comment]
Is there a way to grab a dump when it OOMs? I could take a look at the dump to see what takes up memory.

**Comment by alexperovich** [comment]
I might be able to get a memory dump, but it wouldn't be easy. Its OOMing from inside the XmlSupport.Generate, through GenerateResxFiles. I bet there is just a massive resx file its processing and the Microsoft.Language.Xml stuff doesn't handle it well.

**Comment by KirillOsenkov** [comment]
Ah, it’s a good insight. We should limit processing to files under 1MB or something.

**Comment by KirillOsenkov** [comment]
@alexperovich in this commit I turn off XML processing for files larger than 1 MB: 
https://github.com/KirillOsenkov/SourceBrowser/commit/ad901faf42a0d3e516b7d856f626f427e724eee2

I think it should help with those OOMs.

**Comment by kirsan31** [comment]
It's seems that main problem is solved, so I close this.
