### ISSUE TITLE
Completely broken.

### ISSUE THREAD

**Issue by Alex-ABWorld** [dotnet/source-indexer#73]
Trying to access basic types such as "String" or "Stream" fails. All it finds is a load of tests. Almost nothing is accessible.

**Comment by alexperovich** [comment]
In what way is Stream missing? https://source.dot.net/#System.Private.CoreLib/Stream.cs,f956b0c07e86df64

**Comment by Alex-ABWorld** [comment]
It looks like it's been fixed now, but it wasn't finding anything previously.

**Comment by PathogenDavid** [comment]
I noticed this yesterday too, it was probably related to the Azure Artifacts service outage: https://github.com/dotnet/runtime/issues/44700
