### ISSUE TITLE
source.dot.net hasn't updated in over a week

### ISSUE THREAD

**Issue by stephentoub** [dotnet/source-indexer#76]

**Comment by alexperovich** [comment]
This needs to merge https://github.com/dotnet/runtime/pull/46823

**Comment by stephentoub** [comment]
That was merged a week ago.  What needs to happen now?

**Comment by alexperovich** [comment]
This job has to run successfully https://dev.azure.com/dnceng/internal/_build/results?buildId=1001315&view=logs&j=316d5c15-0c50-544e-8051-e6b14a1ab674&t=657dbd0b-e93c-5e59-4ba8-77889f010efc. It did. The indexer build was broken by the winforms master->main rename though, so I need to fix that.

**Comment by alexperovich** [comment]
Somehow the alerts that were telling me when the build failed went missing. I put them back. The build is now failing because the binlog version one of the repos spits out is too new. I will update that package.

**Comment by alexperovich** [comment]
This should be updated now. The build is still having intermittent problems, I will keep working on it.
