### ISSUE TITLE
AspNetCore source code no longer found

### ISSUE THREAD

**Issue by Codinkat** [dotnet/source-indexer#77]
Since a day or two, the source code of AspNetCore is no longer found on source.dot.net web site. Even providing the exact url returns no result. For example, trying to search ComponentBase (for Blazor framework) returns nothing.

**Comment by alexperovich** [comment]
Asp.net core changed something about their build that broke it.

> Preparing Repository aspnetcore
  cmd /c "build.cmd -BinaryLog -BuildManaged -NoBuildNative -NoBuildNodeJS -NoBuildJava"
  'build.cmd' is not recognized as an internal or external command,
  operable program or batch file.
  The command "cmd /c "build.cmd -BinaryLog -BuildManaged -NoBuildNative -NoBuildNodeJS -NoBuildJava"" exited with code 1.

**Comment by Codinkat** [comment]
It seems that master branch no longer have a "build.cmd" file

**Comment by stephentoub** [comment]
> It seems that master branch no longer have a "build.cmd" file

The main branch in dotnet/aspnetcore is now "main" rather than "master".

**Comment by Codinkat** [comment]
Oops yes! But even "main" do not have a "build.cmd" file :-(

**Comment by Codinkat** [comment]
If it can help, if found this commit. They talk about moving the top-level cmd to project specific cmd files:

https://github.com/dotnet/aspnetcore/pull/29918

**Comment by Codinkat** [comment]
Looking at the files changed section, it seems that build.cmd is now under /eng/build.cmd

https://github.com/dotnet/aspnetcore/pull/29918/files

![image](https://user-images.githubusercontent.com/46028532/109361104-60b61b80-7856-11eb-8ee1-15b27f5676a0.png)

**Comment by Codinkat** [comment]
Some info again. Hope this helps ;-)

https://github.com/dotnet/aspnetcore/commit/0801cea403b2242355bb2f9814cbf174616cc1ac

![image](https://user-images.githubusercontent.com/46028532/109361783-a3c4be80-7857-11eb-8442-61bd44de348b.png)

**Comment by alexperovich** [comment]
I fixed the path, the next build should work.

**Comment by Codinkat** [comment]
@alexperovich Does slash/backslash make a difference? I see that for aspnetcore:

`eng/build.cmd`

...while elsewhere in the same file that backslash is used: ((performance repository)

`$(ArcadeBuildCmd) -projects src\benchmarks\micro\MicroBenchmarks.sln`

**Comment by alexperovich** [comment]
it shouldn't matter. It runs on windows so it works with both slashes.

**Comment by davidfowl** [comment]
It's still broken 😢

**Comment by alexperovich** [comment]
The build is quite unstable right now. I'm trying to figure out why.

**Comment by alexperovich** [comment]
I'm not having a lot of success. The build is deadlocking during indexing with surprising regularity. This has happened before, but not to the point where every build is failing.

**Comment by Codinkat** [comment]
Seems to work now :-)

**Comment by alexperovich** [comment]
The build finally completed successfully. I am still working on resolving the deadlock.

**Comment by Codinkat** [comment]
Glad to see the site back! It is of incredible value to gain a thorough understanding of the NET framework ;-)
