### ISSUE TITLE
All Sources Missing

### ISSUE THREAD

**Issue by Alex-ABPerson** [dotnet/source-indexer#82]
All sources except tests appear to be missing

**Comment by kirsan31** [comment]
For now something has appeared, but a very small part.

**Comment by ViktorHofer** [comment]
cc @alexperovich

**Comment by alexperovich** [comment]
Its the runtime stuff thats all missing. There was another binlog update that broke things. This should fix things https://github.com/dotnet/arcade/pull/7520.

**Comment by kirsan31** [comment]
It's seems working now, thanks.

**Comment by ericstj** [comment]
Yes, thank you @alexperovich!
