### ISSUE TITLE
source.dot.net hasn't updated in over two weeks

### ISSUE THREAD

**Issue by stephentoub** [dotnet/source-indexer#83]
cc: @alexperovich, @Chrisboh, @danmoseley

**Comment by danmoseley** [comment]
@Chrisboh @alexperovich is it still sending emails when the build fails? And can you also add us to the subscription (I used to be on it but the build definition apparently changed)

Perhaps it would be good to define our shared expectations for availability/freshness.

**Comment by alexperovich** [comment]
It is failing, I need to sync the latest changes from kirill's branch but I have been busy with FR the past 2 weeks. I will try to get it done this week.

I have been getting the failure mails. It doesn't look like I can add more people to the list. I'd rather not set up a "spam the entire team" notification, so I think they need to be manually made for each person who wants them. They can be managed here: https://dev.azure.com/dnceng/_usersSettings/notifications

**Comment by danmoseley** [comment]
What's the build definition we should subscribe to?

**Comment by alexperovich** [comment]
its this guy https://dev.azure.com/dnceng/internal/_build?definitionId=612

**Comment by danmoseley** [comment]
OK hopefully this does it. FYI @stephentoub. Although if it fails, I think it will just help us know it's broken earlier.

![image](https://user-images.githubusercontent.com/6385855/126239067-4e9cdb5c-992e-491f-8be5-ee4f0b1f9cec.png)

**Comment by alexperovich** [comment]
I updated to the latest SourceBrowser sources and things are working again.

**Comment by danmoseley** [comment]
Just curious, what caused it to fail?

**Comment by alexperovich** [comment]
This issue https://github.com/KirillOsenkov/SourceBrowser/issues/187
nuget updated and added more errors.
