### ISSUE TITLE
Missing System.Enum

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/source-indexer#84]
`System.Enum` is missing in https://source.dot.net/

**Comment by alexperovich** [comment]
How is it missing? https://source.dot.net/#System.Private.CoreLib/Enum.cs,36729210e317a805

**Comment by paulomorgado** [comment]
It wasn't when I opened the issue.

**Comment by paulomorgado** [comment]
Not even https://source.dot.net/#q=System.Enum was working. But now it is.
