### ISSUE TITLE
source.dot.net hasn't updated in weeks

### ISSUE THREAD

**Issue by stephentoub** [dotnet/source-indexer#86]
For example, this code was merged into dotnet/runtime main three weeks ago:
https://github.com/dotnet/runtime/blame/39a4a705894651490d36c3e4822f1953ef557d8b/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs#L76-L80
but doesn't show up here:
https://source.dot.net/#System.Text.RegularExpressions/System/Text/RegularExpressions/Regex.cs,71

cc: @danmoseley, @alexperovich

**Comment by alexperovich** [comment]
Thats.... very odd. The build says it indexed that version... Let me check things.

**Comment by alexperovich** [comment]
From everything I can see, this job https://dev.azure.com/dnceng/internal/_build/results?buildId=1456410&view=logs&j=316d5c15-0c50-544e-8051-e6b14a1ab674&t=4e01507e-10cc-507d-f6d0-adc59e92bcb8 indexed a very old sha dotnet/runtime#c5a20f916b465707919aa5b6a78f7c4c7675c423

**Comment by alexperovich** [comment]
It uploads the repo's HEAD sha as a file in the uploaded zip, and thats what it shows. This is very odd.

**Comment by alexperovich** [comment]
O, I know what happened. the release/6.0 build ran the index too. I thought I had stopped that.

**Comment by alexperovich** [comment]
https://github.com/dotnet/runtime/pull/61271 will fix it, but we probably have to wait.

**Comment by alexperovich** [comment]
This has been fixed.

**Comment by stephentoub** [comment]
Thanks, @alexperovich.

**Comment by danmoseley** [comment]
I just noticed that change is into release/6.0. Don't we want to index main in all cases?

**Comment by danmoseley** [comment]
Oops, I read it backwards. sounds good
