### ISSUE TITLE
MSBuild sources not indexed

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/source-indexer#87]
Hey @alexperovich MSBuild disappeared from https://source.dot.net. 

Search for "BinaryLogger" yields no results.

Anything I can help look at? I'd look but I don't know where to look.

**Comment by alexperovich** [comment]
It looks like the build command in msbuild is failing.
{"$id":"1","innerException":null,"message":"Cannot find the file RoslynTools.MSBuild.17.0.0.nupkg in package 'RoslynTools.MSBuild 17.0.0' in feed 'dotnet-eng'","typeName":"Microsoft.VisualStudio.Services.Packaging.Shared.WebApi.Exceptions.PackageNotFoundException, Microsoft.VisualStudio.Services.Packaging.Shared.WebApi","typeKey":"PackageNotFoundException","errorCode":0,"eventId":3000}

**Comment by KirillOsenkov** [comment]
@Forgind have you seen this before?

**Comment by Forgind** [comment]
/cc: @dotnet/kitten 

No, I don't think so. It should be looking for 17.1.0.0, right? Maybe a subscription is wrong, and it's looking in the wrong place?

**Comment by KirillOsenkov** [comment]
@alexperovich I found that the MSBuild repo has started requiring VS 2022, and switching the pipeline to `windows-2022` should fix this. Would you mind trying that?

**Comment by KirillOsenkov** [comment]
Note that `windows-latest` hasn't been switch to 2022 yet, so that won't work.

**Comment by KirillOsenkov** [comment]
FYI @stephentoub @danmoseley @alexperovich

**Comment by alexperovich** [comment]
This has been fixed.
