### ISSUE TITLE
Source index hasn't updated in over a week

### ISSUE THREAD

**Issue by stephentoub** [dotnet/source-indexer#91]
cc: @alexperovich, @danmoseley

**Comment by stephentoub** [comment]
> this was resolved right?

It was, but now it appears to be an issue again... seems like the index again hasn't been updated in at least two weeks 😦

**Comment by alexperovich** [comment]
It has an intermittent issue caused by msbuild escaping issues and SAS tokens. I am testing a fix now.

**Comment by alexperovich** [comment]
My fix worked, the website is up-to-date now.

**Comment by stephentoub** [comment]
Thanks.
